// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChannelController from "./channel_controller"
application.register("channel", ChannelController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MentionsController from "./mentions_controller"
application.register("mentions", MentionsController)

import TimeController from "./time_controller"
application.register("time", TimeController)

import UnreadsController from "./unreads_controller"
application.register("unreads", UnreadsController)

import WritingController from "./writing_controller"
application.register("writing", WritingController)
